### PR TITLE
Update middlewares to latest stable versions

### PR DESCRIPTION
**Pull request by fmartinou**
This PR is a try to update most middlewares used by Sentry to latest stable versions.
[As mentioned in the forum](https://forum.sentry.io/t/middleware-version-compatibility/14353/2) I didn't update Postgresql & Clickhouse due to known issues.

I also :
- changed versions to immutable tags (MAJOR.MINOR.PATCH semver versions when possible).
- changed nginx to the Alpine variant

### CODE REVIEW

**Review by BYK — APPROVED** [review]
Thanks a lot for doing this, LGTM!

**Comment by fmartinou** [comment]
I don't get which container or command line is causing the ` OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "service": executable file not found in $PATH: unknown` error.

Could you point me in the right direction?

**Comment by fmartinou** [comment]
Thanks! 👍

**Comment by BYK** [comment]
Thank _you_ @fmartinou!

**Pull request merged**
