### PR TITLE
data doesn't mounted to data directory

### PR DESCRIPTION
**Pull request by mofelee**
We should put data configuration back or update readme.

https://github.com/getsentry/onpremise/pull/105

### CODE REVIEW

**Comment by revolunet** [comment]
Why not volumes ?

"If you are developing new Docker applications, consider using named volumes instead"

https://docs.docker.com/storage/bind-mounts/

**Comment by mofelee** [comment]
@revolunet 
I have no inclination in whether or not to use named volumes. If you want to use it, I think we should to modify the readme. 😄 

image

**Comment by revolunet** [comment]
Thanks, indeed

**Comment by mattrobenolt** [comment]
I would much rather just update the README and maintain using volumes.

**Pull request closed without merging**
