### PR TITLE
Update to 8.17

### PR DESCRIPTION
**Pull request by jamesepatrick**
`sentry.conf.py` is pulled from https://github.com/getsentry/docker-sentry/tree/master/8.17

### CODE REVIEW

**Comment by mattrobenolt** [comment]
The sentry.conf.py changes are wrong here. I just merged https://github.com/getsentry/onpremise/pull/42 instead. I somehow missed that.

**Comment by jamesepatrick** [comment]
Sounds good thank @mattrobenolt 

Out of curiosity how do you mean `sentry.conf.py` are wrong here?

**Comment by jamesepatrick** [comment]
Whoops forgot to close

**Comment by mattrobenolt** [comment]
Meh, sorry about that, I guess I thought it was wrong too fast. I forgot that we handle it correctly now. Lemme reopen and merge.

**Pull request merged**
