### PR TITLE
fix: Ensure snuba cleanup job runs on the correct storage

### PR DESCRIPTION
**Pull request by lynnagara**
Follow up to #920.

### CODE REVIEW

**Review by BYK — APPROVED** [review]
Do we need a cleanup job for transactions storage?

**Comment by lynnagara** [comment]
> Do we need a cleanup job for transactions storage?

Yeah, it would be good to add a job for that too

**Comment by BYK** [comment]
@lynnagara can you guide me to add that?

**Comment by lynnagara** [comment]
@BYK The command would be exactly the same as this line, but with `--storage transactions` instead of `--storage errors`

**Pull request merged**
