### PR TITLE
Unfrobulate CI

### PR DESCRIPTION
**Pull request by chadwhitacre**
Haven't gotten a clean test run yet over on #766. Time to investigate ...

### CODE REVIEW

**Comment by chadwhitacre** [comment]
😏

Screen Shot 2020-12-11 at 3 05 58 PM

https://github.com/docker/compose/issues/3586

**Comment by chadwhitacre** [comment]
↳ https://github.com/docker/compose/pull/3956
 &nbsp; ↳ https://github.com/docker/docker-py/compare/1.10.2...1.10.3
 &nbsp; &nbsp; ↳ https://github.com/docker/docker-py/issues/1207

**Comment by chadwhitacre** [comment]
> Not sure what the solution is tho, we may try to reduce the concurrency again and see what happens

**Comment by BYK** [comment]
Seems like what I did helps but slows things down a bit. WDYT @chadwhitacre, acceptable?

**Comment by chadwhitacre** [comment]
slow and working > fast and broken

**Comment by chadwhitacre** [comment]
slow and working > fast and flakey > never-ending 😩

**Comment by BYK** [comment]
Okay, this seems to have fixed it. I'll re run the checks and see if this holds.

**Comment by chadwhitacre** [comment]
Still failing with "Pool is closed." 😞

giphy

**Pull request merged**
