### PR TITLE
Update deprecated filestore settings

### PR DESCRIPTION
**Pull request by gentlecat**

### CODE REVIEW

**Comment by JeanFred** [comment]
I encountered the same thing as well and made the same changes :)

**Comment by mattrobenolt** [comment]
Ah, technically, this is ok as-is, but I'll update. Thanks for the nudge!

**Comment by mattrobenolt** [comment]
This was more properly synced with https://github.com/getsentry/onpremise/commit/8186ee21e8f62eb195242269608f3105b4f0c3a2

**Comment by gentlecat** [comment]
Thanks!

**Pull request closed without merging**
