### PR TITLE
Fixed CPU soft limit check

### PR DESCRIPTION
**Pull request by ktmitton**

### CODE REVIEW

**Review by BYK — APPROVED** [review]
Wow, such embarrassment on my end! 😓 

Thanks a lot @ktmitton!

**Comment by ktmitton** [comment]
@BYK np!

It's kind of a miracle I caught it. I was just looking over the script on my phone last night because I was curious what it was doing, and somehow that stuck out in the middle of everything else the script is doing.

**Comment by BYK** [comment]
>It's kind of a miracle I caught it. I was just looking over the script on my phone last night because I was curious what it was doing, and somehow that stuck out in the middle of everything else the script is doing.

Hah, I consider ourselves quite lucky then! Btw. if you see things we can improve in the script, including readability and comments, feel free to ping us with issues or pull requests. 🥳

**Comment by ktmitton** [comment]
> > It's kind of a miracle I caught it. I was just looking over the script on my phone last night because I was curious what it was doing, and somehow that stuck out in the middle of everything else the script is doing.
> 
> Hah, I consider ourselves quite lucky then! Btw. if you see things we can improve in the script, including readability and comments, feel free to ping us with issues or pull requests. 🥳

Can do!

And thanks for the quick responses. Was not expecting this to be merged so soon!

**Pull request merged**
