### PR TITLE
ref(config): Switch to Compose config from volume mounts

### LINKED ISSUE #449: Configuration file does not exist while setting up database in ./install.sh
The same script works in GCP host but fails with following error in the on-premise server host.
I followed all the same steps in both, which I found in sentry self-hosted documentation. The only difference is that there are more restrictions on the internet in the host with this error.

```
Checking minimum requirements...
Removing network onpremise_default
Network onpremise_default not found.
Removing network sentry_onpremise_default
Network sentry_onpremise_default not found.

Creating volumes for persistent storage...
Created sentry-data.
Created sentry-postgres.
Created sentry-redis.
Created sentry-zookeeper.
Created sentry-kafka.
Created sentry-clickhouse.
Created sentry-symbolicator.

sentry/sentry.conf.py already exists, skipped creation.
sentry/config.yml already exists, skipped creation.
sentry/requirements.txt already exists, skipped creation.

Fetching and updating Docker images...

Some service image(s) must be built from source by running:
    docker-compose build snuba-cleanup ingest-consumer worker web sentry-cleanup post-process-forwarder cron symbolicator-cleanup
latest: Pulling from getsentry/sentry
8d691f585fa8: Pulling fs layer
3fd6980f9df6: Pulling fs layer
c4f890363b98: Pulling fs layer
b8cfb9853b0a: Pulling fs layer
f235248cf522: Pulling fs layer
66faa48e3ae9: Pulling fs layer
b1876d473656: Pulling fs layer
424dca760285: Pulling fs layer
cd721e9af9b4: Pulling fs layer
c2c6e238cafb: Pulling fs layer
4c8ac92dc998: Pulling fs layer
fa155f8a6a45: Pulling fs layer
9fa7f6f7b21d: Pulling fs layer
4c8ac92dc998: Waiting
fa155f8a6a45: Waiting
9fa7f6f7b21d: Waiting
b8cfb9853b0a: Waiting
f235248cf522: Waiting
b1876d473656: Waiting
424dca760285: Waiting
66faa48e3ae9: Waiting
cd721e9af9b4: Waiting
c2c6e238cafb: Waiting
3fd6980f9df6: Verifying Checksum
3fd6980f9df6: Download complete
8d691f585fa8: Verifying Checksum
8d691f585fa8: Download complete
c4f890363b98: Verifying Checksum
c4f890363b98: Download complete
8d691f585fa8: Pull complete
b8cfb9853b0a: Verifying Checksum
b8cfb9853b0a: Download complete
f235248cf522: Verifying Checksum
f235248cf522: Download complete
3fd6980f9df6: Pull complete
66faa48e3ae9: Verifying Checksum
66faa48e3ae9: Download complete
c4f890363b98: Pull complete
b8cfb9853b0a: Pull complete
f235248cf522: Pull complete
b1876d473656: Verifying Checksum
b1876d473656: Download complete
66faa48e3ae9: Pull complete
b1876d473656: Pull complete
424dca760285: Verifying Checksum
424dca760285: Download complete
c2c6e238cafb: Verifying Checksum
c2c6e238cafb: Download complete
4c8ac92dc998: Download complete
cd721e9af9b4: Verifying Checksum
cd721e9af9b4: Download complete
fa155f8a6a45: Verifying Checksum
fa155f8a6a45: Download complete
9fa7f6f7b21d: Verifying Checksum
9fa7f6f7b21d: Download complete
424dca760285: Pull complete
cd721e9af9b4: Pull complete
c2c6e238cafb: Pull complete
4c8ac92dc998: Pull complete
fa155f8a6a45: Pull complete
9fa7f6f7b21d: Pull complete
Digest: sha256:3c3dfe251ae04f0e1c8795d40e22bf76911bd12bad9b097183d6af33ff2272e1
Status: Downloaded newer image for getsentry/sentry:latest
docker.io/getsentry/sentry:latest

Building and tagging Docker images...

Building web
Step 1/4 : ARG SENTRY_IMAGE
Step 2/4 : FROM ${SENTRY_IMAGE:-getsentry/sentry:latest}
 ---> c09ef308d23b
Step 3/4 : COPY . /usr/src/sentry
 ---> 6c1ba3aa21f8
Step 4/4 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Running in 4a6a5fc1cb89
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Removing intermediate container 4a6a5fc1cb89
 ---> 20dfa3b07450

Successfully built 20dfa3b07450
Successfully tagged sentry-onpremise-local:latest
smtp uses an image, skipping
memcached uses an image, skipping
redis uses an image, skipping
postgres uses an image, skipping
zookeeper uses an image, skipping
kafka uses an image, skipping
clickhouse uses an image, skipping
snuba-api uses an image, skipping
snuba-consumer uses an image, skipping
snuba-outcomes-consumer uses an image, skipping
snuba-replacer uses an image, skipping
symbolicator uses an image, skipping
relay uses an image, skipping
nginx uses an image, skipping
Building snuba-cleanup          ...
Building symbolicator-cleanup   ...
Building web                    ...
Building cron                   ...
Building worker                 ...
Building ingest-consumer        ...
Building post-process-forwarder ...
Building sentry-cleanup         ...
Building worker
Building post-process-forwarder
Building snuba-cleanup
Building sentry-cleanup
Building web
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 20dfa3b07450
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
Step 1/4 : ARG SENTRY_IMAGE
Step 2/4 : FROM ${SENTRY_IMAGE:-getsentry/sentry:latest}
 ---> c09ef308d23b
Step 3/4 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 6c1ba3aa21f8
Step 4/4 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 20dfa3b07450

Successfully built 20dfa3b07450
Successfully tagged sentry-onpremise-local:latest
Building post-process-forwarder ... done
Building ingest-consumer
Step 1/4 : ARG SENTRY_IMAGE
Step 2/4 : FROM ${SENTRY_IMAGE:-getsentry/sentry:latest}
 ---> c09ef308d23b
Step 3/4 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 6c1ba3aa21f8
Step 4/4 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 20dfa3b07450

Successfully built 20dfa3b07450
Successfully tagged sentry-onpremise-local:latest
Building worker                 ... done
Building cron
Step 1/4 : ARG SENTRY_IMAGE
Step 2/4 : FROM ${SENTRY_IMAGE:-getsentry/sentry:latest}
 ---> Running in 36d6fa3346cd
 ---> c09ef308d23b
Step 3/4 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 6c1ba3aa21f8
Step 4/4 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 20dfa3b07450

Successfully built 20dfa3b07450
Successfully tagged sentry-onpremise-local:latest
Building web                    ... done
Building symbolicator-cleanup
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> e4db2eaa424c
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Running in 51f8a81ba964
Step 1/4 : ARG SENTRY_IMAGE
Step 2/4 : FROM ${SENTRY_IMAGE:-getsentry/sentry:latest}
 ---> c09ef308d23b
Step 3/4 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 6c1ba3aa21f8
Step 4/4 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 20dfa3b07450

Successfully built 20dfa3b07450
Successfully tagged sentry-onpremise-local:latest
Building cron                   ... done
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> db619b07560e
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
Step 1/4 : ARG SENTRY_IMAGE
Step 2/4 : FROM ${SENTRY_IMAGE:-getsentry/sentry:latest}
 ---> c09ef308d23b
Step 3/4 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 6c1ba3aa21f8
Step 4/4 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> 20dfa3b07450

Successfully built 20dfa3b07450
Successfully tagged sentry-onpremise-local:latest
Building ingest-consumer        ... done
 ---> Running in c39b0bbfa51d
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:2 http://security.debian.org/debian-security buster/updates/main amd64 Packages [189 kB]
Get:2 http://security.debian.org/debian-security buster/updates/main amd64 Packages [189 kB]
Get:2 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [523 kB]
Get:3 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster InRelease [122 kB]
Ign:3 http://deb.debian.org/debian stretch InRelease
Get:4 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:5 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian stretch-updates/main amd64 Packages [27.9 kB]
Get:7 http://deb.debian.org/debian stretch Release.gpg [2410 B]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [7083 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7380 B]
Fetched 8339 kB in 2s (3377 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  lsb-base sensible-utils
Suggested packages:
  anacron logrotate checksecurity
Recommended packages:
  default-mta | mail-transport-agent
Fetched 7940 kB in 4s (1935 kB/s)
Reading package lists...The following NEW packages will be installed:
  cron lsb-base sensible-utils
0 upgraded, 3 newly installed, 0 to remove and 12 not upgraded.
Need to get 143 kB of archives.
After this operation, 383 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 sensible-utils all 0.0.12 [15.8 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 lsb-base all 10.2019051400 [28.4 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7380 B]
Get:3 http://deb.debian.org/debian buster/main amd64 cron amd64 3.0pl1-134+deb10u1 [99.0 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 143 kB in 0s (455 kB/s)
Selecting previously unselected package sensible-utils.
(Reading database ... 11918 files and directories currently installed.)
Preparing to unpack .../sensible-utils_0.0.12_all.deb ...
Unpacking sensible-utils (0.0.12) ...

Selecting previously unselected package lsb-base.
Preparing to unpack .../lsb-base_10.2019051400_all.deb ...
Unpacking lsb-base (10.2019051400) ...
Reading package lists...Selecting previously unselected package cron.
Preparing to unpack .../cron_3.0pl1-134+deb10u1_amd64.deb ...
Unpacking cron (3.0pl1-134+deb10u1) ...
Setting up lsb-base (10.2019051400) ...
Setting up sensible-utils (0.0.12) ...
Setting up cron (3.0pl1-134+deb10u1) ...
Adding group `crontab' (GID 101) ...
Done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Removing intermediate container 36d6fa3346cd
 ---> d0cd35c102b9
Step 4/5 : COPY entrypoint.sh /entrypoint.sh

Building dependency tree...
Reading state information...
 ---> 7e57d812a9fe
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
Suggested packages:
  anacron logrotate checksecurity
Recommended packages:
  exim4 | postfix | mail-transport-agent
The following NEW packages will be installed:
  cron
 ---> Running in af7848506827
Removing intermediate container af7848506827
 ---> 6f26d12d3a71

Successfully built 6f26d12d3a71
Successfully tagged sentry-cleanup-onpremise-local:latest
Building sentry-cleanup         ... done
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 95.4 kB of archives.
After this operation, 257 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 cron amd64 3.0pl1-128+deb9u1 [95.4 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 95.4 kB in 0s (742 kB/s)
Selecting previously unselected package cron.
(Reading database ... 6684 files and directories currently installed.)
Preparing to unpack .../cron_3.0pl1-128+deb9u1_amd64.deb ...
Unpacking cron (3.0pl1-128+deb9u1) ...
Fetched 8339 kB in 6s (1419 kB/s)
Reading package lists...Setting up cron (3.0pl1-128+deb9u1) ...
Adding group `crontab' (GID 101) ...
Done.
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Removing intermediate container c39b0bbfa51d
 ---> 4467ec3170a7
Step 4/5 : COPY entrypoint.sh /entrypoint.sh

Reading package lists... ---> 9d2e1b6660e7
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Running in 97fad6e24e93
Removing intermediate container 97fad6e24e93
 ---> 438a21a5741d

Successfully built 438a21a5741d
Successfully tagged symbolicator-cleanup-onpremise-local:latest
Building symbolicator-cleanup   ... done

Building dependency tree...
Reading state information...
The following additional packages will be installed:
  sensible-utils
Suggested packages:
  anacron logrotate checksecurity
Recommended packages:
  default-mta | mail-transport-agent
The following NEW packages will be installed:
  cron sensible-utils
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 115 kB of archives.
After this operation, 333 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 sensible-utils all 0.0.12 [15.8 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 cron amd64 3.0pl1-134+deb10u1 [99.0 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 115 kB in 0s (459 kB/s)
Selecting previously unselected package sensible-utils.
(Reading database ... 6849 files and directories currently installed.)
Preparing to unpack .../sensible-utils_0.0.12_all.deb ...
Unpacking sensible-utils (0.0.12) ...
Selecting previously unselected package cron.
Preparing to unpack .../cron_3.0pl1-134+deb10u1_amd64.deb ...
Unpacking cron (3.0pl1-134+deb10u1) ...
Setting up sensible-utils (0.0.12) ...
Setting up cron (3.0pl1-134+deb10u1) ...
Adding group `crontab' (GID 101) ...
Done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Removing intermediate container 51f8a81ba964
 ---> 5c59510d27af
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> b122c9da3d69
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Running in b00bd9b14339
Removing intermediate container b00bd9b14339
 ---> 781495a8a88b

Successfully built 781495a8a88b
Successfully tagged snuba-cleanup-onpremise-local:latest
Building snuba-cleanup          ... done

Docker images built.
Bootstrapping Snuba...
Creating network "sentry_onpremise_default" with the default driver
Creating volume "sentry_onpremise_sentry-secrets" with default driver
Creating volume "sentry_onpremise_sentry-smtp" with default driver
Creating volume "sentry_onpremise_sentry-zookeeper-log" with default driver
Creating volume "sentry_onpremise_sentry-kafka-log" with default driver
Creating volume "sentry_onpremise_sentry-smtp-log" with default driver
Creating volume "sentry_onpremise_sentry-clickhouse-log" with default driver
Creating sentry_onpremise_zookeeper_1 ...
Creating sentry_onpremise_redis_1     ...
Creating sentry_onpremise_clickhouse_1 ...
Creating sentry_onpremise_clickhouse_1 ... done
Creating sentry_onpremise_zookeeper_1  ... done
Creating sentry_onpremise_kafka_1      ...
Creating sentry_onpremise_kafka_1      ... done
Creating sentry_onpremise_redis_1      ... done
+ '[' b = - ']'
+ snuba bootstrap --help
+ set -- snuba bootstrap --force
+ set gosu snuba snuba bootstrap --force
+ exec gosu snuba snuba bootstrap --force
2020-04-27 07:32:59,225 Connection to Kafka failed (attempt 0)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 55, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
2020-04-27 07:33:01,229 Connection to Kafka failed (attempt 1)
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/cli/bootstrap.py", line 55, in bootstrap
    client.list_topics(timeout=1)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
2020-04-27 07:33:02,440 Topic cdc created
2020-04-27 07:33:02,440 Topic ingest-sessions created
2020-04-27 07:33:02,440 Topic events created
2020-04-27 07:33:02,441 Topic errors-replacements created
2020-04-27 07:33:02,441 Topic event-replacements created
2020-04-27 07:33:02,441 Topic snuba-commit-log created
2020-04-27 07:33:02,441 Topic outcomes created
2020-04-27 07:33:02,463 Tables for dataset groupassignee created.
2020-04-27 07:33:02,465 Tables for dataset outcomes_raw created.
2020-04-27 07:33:02,473 Tables for dataset sessions created.
2020-04-27 07:33:02,475 Tables for dataset groupedmessage created.
2020-04-27 07:33:02,483 Tables for dataset discover created.
2020-04-27 07:33:02,486 Tables for dataset transactions created.
2020-04-27 07:33:02,490 Tables for dataset events_migration created.
2020-04-27 07:33:02,493 Tables for dataset events created.
2020-04-27 07:33:02,498 Tables for dataset outcomes created.
Starting sentry_onpremise_redis_1 ...
Starting sentry_onpremise_zookeeper_1 ...
Starting sentry_onpremise_redis_1     ... done
Starting sentry_onpremise_zookeeper_1 ... done
Starting sentry_onpremise_clickhouse_1 ...
Starting sentry_onpremise_clickhouse_1 ... done
Starting sentry_onpremise_kafka_1      ...
Starting sentry_onpremise_kafka_1      ... done
+ '[' m = - ']'
+ snuba migrate --help
+ set -- snuba migrate
+ set gosu snuba snuba migrate
+ exec gosu snuba snuba migrate
2020-04-27 07:33:07,104 Migrating dataset events
2020-04-27 07:33:07,154 Migrating dataset events_migration
2020-04-27 07:33:07,181 Migrating dataset transactions
2020-04-27 07:33:07,194 Migrating dataset groupedmessage
2020-04-27 07:33:07,201 Migrating dataset sessions
2020-04-27 07:33:07,213 Migrating dataset groupassignee
2020-04-27 07:33:07,219 Migrating dataset outcomes
2020-04-27 07:33:07,227 Migrating dataset discover
2020-04-27 07:33:07,252 Migrating dataset outcomes_raw


Setting up database...
Starting sentry_onpremise_zookeeper_1 ...
Starting sentry_onpremise_clickhouse_1 ...
Starting sentry_onpremise_zookeeper_1  ... done
Starting sentry_onpremise_clickhouse_1 ... done
Creating sentry_onpremise_memcached_1  ...
Starting sentry_onpremise_redis_1      ...
Creating sentry_onpremise_postgres_1   ...
Starting sentry_onpremise_redis_1      ... done
Creating sentry_onpremise_smtp_1       ...
Starting sentry_onpremise_kafka_1      ...
Creating sentry_onpremise_symbolicator_1 ...
Starting sentry_onpremise_kafka_1        ... done
Creating sentry_onpremise_snuba-consumer_1 ...
Creating sentry_onpremise_snuba-replacer_1 ...
Creating sentry_onpremise_snuba-api_1      ...
Creating sentry_onpremise_snuba-outcomes-consumer_1 ...
Creating sentry_onpremise_memcached_1               ... done
Creating sentry_onpremise_smtp_1                    ... done
Creating sentry_onpremise_symbolicator_1            ... done
Creating sentry_onpremise_snuba-consumer_1          ... done
Creating sentry_onpremise_snuba-outcomes-consumer_1 ... done
Creating sentry_onpremise_snuba-replacer_1          ... done
Creating sentry_onpremise_postgres_1                ... done
Creating sentry_onpremise_snuba-api_1               ... done
Error: Configuration file does not exist. Use 'sentry init' to initialize the file.
Cleaning up...
```

I did no config changes just trying to do the vanilla installation. Also, I tried it many times so I just did docker system prune so that it all happens from the beginning.

The same issue is also reported by another person at [sentry forum]( https://forum.sentry.io/t/issues-with-installing-sentry-on-first-time/9296).

### PR DESCRIPTION
**Pull request by BYK**
Uses https://docs.docker.com/compose/compose-file/#configs to fix #449.

### CODE REVIEW

**Comment by BYK** [comment]
>Some services (cron, ingest-consumer, nginx, post-process-forwarder, relay, sentry-cleanup, web, worker) use the 'configs' key, which will be ignored. Compose does not support 'configs' configuration - use `docker stack deploy` to deploy to a swarm.

LOL, closing :D

**Comment by tomscholz** [comment]
Hi @BYK :),
from where did you get the quote? The docker-compose docs? 

> Some services (cron, ingest-consumer, nginx, post-process-forwarder, relay, sentry-cleanup, web, worker) use the 'configs' key, which will be ignored. Compose does not support 'configs' configuration - use docker stack deploy to deploy to a swarm.

Cheers,
Tom

**Comment by BYK** [comment]
I think this was printed to the terminal when I tried to run v docker-compose up with this PR 😃

**Pull request closed without merging**
